"""Default configuration values for JARVIS OS."""

from __future__ import annotations

from typing import Any, Final


DEFAULT_CONFIG: Final[dict[str, Any]] = {
    "general": {
        "app_name": "JARVIS OS",
        "environment": "development",
        "debug": False,
    },
    "logging": {
        "level": "INFO",
        "log_dir": "logs",
        "log_file": "jarvis-os.log",
        "max_bytes": 1_048_576,
        "backup_count": 5,
    },
    "memory": {
        "enabled": True,
        "storage_dir": "memory",
        "task_store_dir": "data/tasks",
        "vector_index_dir": "data/vector-indexes",
    },
    "brain": {
        "enabled": True,
        "vault_path": "data/obsidian-vault",
        "vault_name": "Jarvis Brain",
        "auto_create_vault": True,
        "daily_note_format": "%Y-%m-%d",
    },
    "models": {
        "default_model": "llama3.2:1b",
        "fallback_model": "",
        "allow_local_models": True,
    },
    "providers": {
        "default_provider": "ollama",
        "enabled_providers": ["ollama"],
        "timeout_seconds": 30,
        "max_retries": 2,
        "track_costs": True,
        "definitions": {
            "openai": {
                "kind": "openai",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.openai.com",
                "api_key_env": "OPENAI_API_KEY",
                "metadata": {
                    "provider_family": "openai",
                },
            },
            "anthropic": {
                "kind": "anthropic",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.anthropic.com",
                "api_key_env": "ANTHROPIC_API_KEY",
                "metadata": {
                    "provider_family": "anthropic",
                },
            },
            "google": {
                "kind": "google_gemini",
                "enabled": False,
                "local_only": False,
                "base_url": "https://generativelanguage.googleapis.com",
                "api_key_env": "GOOGLE_API_KEY",
                "metadata": {
                    "provider_family": "gemini",
                },
            },
            "deepseek": {
                "kind": "deepseek",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.deepseek.com",
                "api_key_env": "DEEPSEEK_API_KEY",
                "metadata": {
                    "provider_family": "deepseek",
                },
            },
            "mistral": {
                "kind": "mistral",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.mistral.ai",
                "api_key_env": "MISTRAL_API_KEY",
                "metadata": {
                    "provider_family": "mistral",
                },
            },
            "groq": {
                "kind": "groq",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.groq.com",
                "api_key_env": "GROQ_API_KEY",
                "metadata": {
                    "provider_family": "groq",
                },
            },
            "openrouter": {
                "kind": "openrouter",
                "enabled": False,
                "local_only": False,
                "base_url": "https://openrouter.ai/api",
                "api_key_env": "OPENROUTER_API_KEY",
                "metadata": {
                    "provider_family": "openrouter",
                },
            },
            "zenmux": {
                "kind": "zenmux",
                "enabled": True,
                "local_only": False,
                "base_url": "https://api.zenmux.ai",
                "api_key_env": "ZENMUX_API_KEY",
                "metadata": {
                    "provider_family": "zenmux",
                },
            },
            "local": {
                "kind": "local",
                "enabled": False,
                "local_only": True,
                "base_url": "http://127.0.0.1:11434",
                "metadata": {
                    "local": True,
                    "runtime": "openai-compatible",
                },
            },
            "ollama": {
                "kind": "ollama",
                "enabled": True,
                "local_only": True,
                "base_url": "http://127.0.0.1:11434",
                "preferred_model": "llama3.2:1b",
                "default_model": "llama3.2:1b",
                "timeout_seconds": 60,
                "max_retries": 1,
                "metadata": {
                    "local": True,
                    "runtime": "ollama",
                },
            },
        },
    },
    "agents": {
        "enabled": True,
        "max_concurrent_agents": 4,
        "workspace_dir": "data/agent-workspaces",
        "max_agents_per_coordination": 4,
        "max_subtasks_per_coordination": 8,
        "max_recursion_depth": 1,
        "max_retries_per_subtask": 1,
        "max_total_timeout_seconds": 180,
    },
    "tools": {
        "maximum_per_request": 3,
        "maximum_per_coordination": 6,
        "maximum_retries": 1,
        "maximum_timeout_seconds": 30,
        "maximum_concurrent": 2,
        "maximum_output_bytes": 64000,
        "maximum_argument_bytes": 16000,
        "maximum_chained_depth": 1,
        "maximum_dry_run_seconds": 5,
        "maximum_history": 200,
    },
    "planning": {"maximum_steps":12,"maximum_milestones":5,"maximum_alternatives":3,"maximum_dependencies_per_step":4,"maximum_plan_depth":2,"maximum_retries":1,"maximum_replans":3,"maximum_concurrent":2,"maximum_agents":3,"maximum_tools":4,"maximum_timeout_seconds":90,"maximum_versions":10,"maximum_output_bytes":100000,"maximum_assumptions":8},
    "voice":{"enabled":False,"mode":"off","language":"en-US","local_only":True,"privacy_mode":"standard","input_enabled":False,"output_enabled":False,"input_backend":"offline-stt","output_backend":"windows-sapi","input_device":None,"output_device":None,"confidence_threshold":0.75,"confirmation_threshold":0.6,"max_capture_seconds":30,"silence_timeout_seconds":3,"max_audio_size":20000000,"max_transcript_length":4000,"max_spoken_response_length":500,"rate":0,"volume":100,"raw_audio_persistence":False,"retention_limit":0,"temp_audio_lifetime_seconds":300,"stt_model_path":None,"stt_executable":None,"wake_word_enabled":False,"wake_word_backend":None,"activation_phrase":"jarvis","interruption_enabled":True,"temp_directory":"data/voice-temp","allowed_audio_directories":["data/voice-input"]},
    "vision":{"enabled":True,"local_only":True,"privacy_mode":"standard","max_image_size":20000000,"timeout_seconds":60,"allowed_directories":[]},
    "interface": {
        "enabled": False,
        "host": "127.0.0.1",
        "port": 8765,
        "open_browser": True,
        "theme": "system",
        "default_view": "chat",
        "event_transport": "sse",
        "max_request_size": 65536,
        "max_response_size": 262144,
        "max_log_entries": 200,
        "max_activity_entries": 200,
        "max_history_messages": 200,
        "request_timeout": 120,
        "event_timeout": 30,
        "allow_remote": False,
        "allowed_origins": ["http://127.0.0.1:8765", "http://localhost:8765"],
        "session_token_lifetime": 14400,
        "safe_markdown": True,
        "show_provider_metadata": True,
        "show_activity_panel": True,
        "compact_mode": False,
    },
    "plugins": {
        "enabled": True,
        "plugin_dir": "plugins",
        "allow_user_plugins": False,
        "auto_discover": True,
        "auto_enable": True,
        "compatibility_version": "0.1",
    },
    "downloads": {
        "download_dir": "data/downloads",
        "max_concurrent_downloads": 3,
        "verify_integrity": True,
    },
    "automation": {
        "enabled": False,
        "queue_dir": "data/automation-queue",
        "max_concurrent_jobs": 2,
    },
    "security": {
        "secrets_dir": "data/secrets",
        "allow_shell_execution": False,
        "allow_network_access": True,
        "require_confirmation_for_installers": True,
    },
    "desktop": {
        "enabled": True,
        "platform": "windows",
        "downloads_folder": "",
    },
    "mobile": {
        "enabled": False,
        "api_enabled": False,
    },
}
