"""Default configuration values for JARVIS OS."""

from __future__ import annotations

from typing import Any, Final


DEFAULT_CONFIG: Final[dict[str, Any]] = {
    "general": {
        "app_name": "JARVIS OS",
        "environment": "development",
        "debug": False,
    },
    "logging": {
        "level": "INFO",
        "log_dir": "logs",
        "log_file": "jarvis-os.log",
        "max_bytes": 1_048_576,
        "backup_count": 5,
    },
    "memory": {
        "enabled": True,
        "storage_dir": "memory",
        "task_store_dir": "data/tasks",
        "vector_index_dir": "data/vector-indexes",
        "local_only": True,
        "auto_remember": False,
        "auto_session_summary": True,
        "max_records": 2000,
        "max_search_results": 12,
        "max_context_items": 8,
        "max_context_chars": 6000,
        "audit_enabled": True,
        "audit_retention": 100,
        "default_retention_days": 3650,
        "sensitive_storage_enabled": False,
        "consolidation_enabled": True,
        "secret_detection_enabled": True,
    },
    "conversation": {
        "enabled": True,
        "max_turns": 12,
        "max_topics": 6,
        "summary_threshold": 8,
        "reference_resolution": True,
        "clarification_enabled": True,
        "max_context_chars": 6000,
    },
    "brain": {
        "enabled": True,
        "vault_path": "data/obsidian-vault",
        "vault_name": "Jarvis Brain",
        "auto_create_vault": True,
        "daily_note_format": "%Y-%m-%d",
    },
    "models": {
        "default_model": "llama3.2:1b",
        "fallback_model": "",
        "allow_local_models": True,
        "enabled": True,
        "local_only_default": True,
        "allow_cloud_providers": False,
        "default_chat_provider": "ollama_text",
        "default_reasoning_provider": "ollama_text",
        "default_coding_provider": "ollama_text",
        "default_vision_provider": "ollama_vision",
        "max_providers": 32,
        "max_models_per_provider": 32,
        "max_route_explanations": 8,
        "hardware_discovery_enabled": True,
    },
    "providers": {
        "default_provider": "ollama",
        "enabled_providers": ["ollama"],
        "timeout_seconds": 30,
        "max_retries": 2,
        "track_costs": True,
        "definitions": {
            "openai": {
                "kind": "openai",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.openai.com",
                "api_key_env": "OPENAI_API_KEY",
                "metadata": {
                    "provider_family": "openai",
                },
            },
            "anthropic": {
                "kind": "anthropic",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.anthropic.com",
                "api_key_env": "ANTHROPIC_API_KEY",
                "metadata": {
                    "provider_family": "anthropic",
                },
            },
            "google": {
                "kind": "google_gemini",
                "enabled": False,
                "local_only": False,
                "base_url": "https://generativelanguage.googleapis.com",
                "api_key_env": "GOOGLE_API_KEY",
                "metadata": {
                    "provider_family": "gemini",
                },
            },
            "deepseek": {
                "kind": "deepseek",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.deepseek.com",
                "api_key_env": "DEEPSEEK_API_KEY",
                "metadata": {
                    "provider_family": "deepseek",
                },
            },
            "mistral": {
                "kind": "mistral",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.mistral.ai",
                "api_key_env": "MISTRAL_API_KEY",
                "metadata": {
                    "provider_family": "mistral",
                },
            },
            "groq": {
                "kind": "groq",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.groq.com",
                "api_key_env": "GROQ_API_KEY",
                "metadata": {
                    "provider_family": "groq",
                },
            },
            "openrouter": {
                "kind": "openrouter",
                "enabled": False,
                "local_only": False,
                "base_url": "https://openrouter.ai/api",
                "api_key_env": "OPENROUTER_API_KEY",
                "metadata": {
                    "provider_family": "openrouter",
                },
            },
            "zenmux": {
                "kind": "zenmux",
                "enabled": True,
                "local_only": False,
                "base_url": "https://api.zenmux.ai",
                "api_key_env": "ZENMUX_API_KEY",
                "metadata": {
                    "provider_family": "zenmux",
                },
            },
            "local": {
                "kind": "local",
                "enabled": False,
                "local_only": True,
                "base_url": "http://127.0.0.1:11434",
                "metadata": {
                    "local": True,
                    "runtime": "openai-compatible",
                },
            },
            "ollama": {
                "kind": "ollama",
                "enabled": True,
                "local_only": True,
                "base_url": "http://127.0.0.1:11434",
                "preferred_model": "llama3.2:1b",
                "default_model": "llama3.2:1b",
                "timeout_seconds": 60,
                "max_retries": 1,
                "metadata": {
                    "local": True,
                    "runtime": "ollama",
                },
            },
        },
    },
    "agents": {
        "enabled": True,
        "max_concurrent_agents": 4,
        "workspace_dir": "data/agent-workspaces",
        "max_agents_per_coordination": 4,
        "max_subtasks_per_coordination": 8,
        "max_recursion_depth": 1,
        "max_retries_per_subtask": 1,
        "max_total_timeout_seconds": 180,
        "default_mode": "plan_only",
        "max_agents": 64,
        "max_capabilities_per_agent": 32,
        "max_output_chars": 8000,
        "require_approval_for_high_risk": True,
        "local_only_default": True,
        "register_future_placeholders": True,
        "show_future_agents": True,
        "max_diagnostic_agents": 25,
        "max_diagnostic_capabilities": 40,
        "default_specialist_mode": "plan_only",
        "block_critical_future_agents": True,
    },
    "prime": {
        "enabled": True,
        "default_execution_mode": "plan_only",
        "max_plan_steps": 8,
        "max_reason_chars": 600,
        "max_fallbacks": 3,
        "require_approval_for_high_risk": True,
        "block_critical_risk": True,
        "local_only": True,
    },
    "skills": {
        "enabled": True,
        "allow_external_plugins": False,
        "allow_mcp": False,
        "default_execution_mode": "plan_only",
        "max_skills": 512,
        "max_capabilities_per_skill": 32,
        "max_output_chars": 8000,
        "require_approval_for_side_effects": True,
        "block_secrets_access": True,
    },
    "research": {
        "enabled": True,
        "default_depth": "standard",
        "max_plan_steps": 5,
        "max_evidence_items": 5,
        "max_snippet_chars": 320,
        "max_summary_chars": 1200,
        "allow_web_read_only": True,
        "allow_external_search_api": False,
        "save_history": True,
        "local_only": True,
        "require_citations_for_web_claims": True,
    },
    "coding": {
        "enabled": True,
        "default_mode": "plan_only",
        "max_plan_steps": 6,
        "max_files_listed": 20,
        "max_diff_chars": 4000,
        "max_history_items": 25,
        "allow_write_operations": False,
        "allow_command_execution": False,
        "require_approval_for_write": True,
        "require_approval_for_push": True,
        "block_secrets_access": True,
    },
    "tools": {
        "maximum_per_request": 3,
        "maximum_per_coordination": 6,
        "maximum_retries": 1,
        "maximum_timeout_seconds": 30,
        "maximum_concurrent": 2,
        "maximum_output_bytes": 64000,
        "maximum_argument_bytes": 16000,
        "maximum_chained_depth": 1,
        "maximum_dry_run_seconds": 5,
        "maximum_history": 200,
    },
    "planning": {"maximum_steps":12,"maximum_milestones":5,"maximum_alternatives":3,"maximum_dependencies_per_step":4,"maximum_plan_depth":2,"maximum_retries":1,"maximum_replans":3,"maximum_concurrent":2,"maximum_agents":3,"maximum_tools":4,"maximum_timeout_seconds":90,"maximum_versions":10,"maximum_output_bytes":100000,"maximum_assumptions":8},
    "voice":{"enabled":False,"mode":"off","language":"en-US","local_only":True,"privacy_mode":"standard","input_enabled":False,"output_enabled":False,"input_backend":"offline-stt","output_backend":"windows-sapi","input_device":None,"output_device":None,"confidence_threshold":0.75,"confirmation_threshold":0.6,"max_capture_seconds":30,"silence_timeout_seconds":3,"max_audio_size":20000000,"max_transcript_length":4000,"max_spoken_response_length":500,"max_auto_speech_chars":12000,"rate":0,"volume":100,"raw_audio_persistence":False,"retention_limit":0,"temp_audio_lifetime_seconds":300,"voice_input_audit_retention":50,"stt_model_path":None,"stt_executable":None,"wake_word_enabled":False,"wake_word_backend":None,"activation_phrase":"jarvis","interruption_enabled":True,"temp_directory":"data/voice-temp","allowed_audio_directories":["data/voice-input"]},
    "vision":{"enabled":True,"local_only":True,"privacy_mode":"standard","provider":"ollama","model":"llava","ollama_host":"http://127.0.0.1:11434","max_image_size":20000000,"timeout_seconds":60,"audit_enabled":True,"audit_retention":100,"store_image_content":False,"allowed_directories":[]},
    "image_generation": {
        "enabled": False,
        "default_provider": "unavailable",
        "local_only": True,
        "output_dir": "data/image_generation",
        "max_prompt_chars": 600,
        "max_negative_prompt_chars": 300,
        "save_metadata": True,
        "allow_overwrite": False,
        "safety_filter_enabled": True,
    },
    "video_editing": {
        "enabled": False,
        "default_provider": "unavailable",
        "local_only": True,
        "output_dir": "data/video_editing",
        "max_prompt_chars": 600,
        "max_source_media_items": 12,
        "save_metadata": True,
        "allow_overwrite": False,
        "safety_filter_enabled": True,
    },
    "sync":{"enabled":False,"mode":"off","adapter":"local-queue","automatic_sync":False,"remote_endpoint":None,"maximum_item_size":8192,"maximum_queue_items":100,"maximum_batch_size":10,"maximum_attempts":3,"completed_retention_count":25,"audit_retention_count":100,"maximum_nested_depth":4,"maximum_string_length":1000,"conflict_strategy":"manual","encryption_required":True,"sync_raw_audio":False,"sync_raw_images":False,"sync_raw_documents":False,"sync_conversations":False,"sync_secrets":False},
    "web_automation":{"enabled":True,"mode":"read_only","adapter":"read-only-http","allow_local_targets":False,"allow_http":False,"audit_retention":100,"action_timeout_seconds":8,"maximum_redirects":5,"maximum_response_bytes":524288,"maximum_preview_characters":2000,"store_page_content":False,"store_screenshots":False},
    "interface": {
        "enabled": False,
        "host": "127.0.0.1",
        "port": 8765,
        "open_browser": True,
        "theme": "system",
        "default_view": "chat",
        "event_transport": "sse",
        "max_request_size": 65536,
        "max_response_size": 262144,
        "max_log_entries": 200,
        "max_activity_entries": 200,
        "max_history_messages": 200,
        "request_timeout": 120,
        "event_timeout": 30,
        "allow_remote": False,
        "allowed_origins": ["http://127.0.0.1:8765", "http://localhost:8765"],
        "session_token_lifetime": 14400,
        "safe_markdown": True,
        "show_provider_metadata": True,
        "show_activity_panel": True,
        "compact_mode": False,
    },
    "plugins": {
        "enabled": True,
        "plugin_dir": "plugins",
        "allow_user_plugins": False,
        "auto_discover": True,
        "auto_enable": True,
        "compatibility_version": "0.1",
    },
    "downloads": {
        "download_dir": "data/downloads",
        "max_concurrent_downloads": 3,
        "verify_integrity": True,
    },
    "automation": {
        "enabled": False,
        "queue_dir": "data/automation-queue",
        "max_concurrent_jobs": 2,
    },
    "security": {
        "secrets_dir": "data/secrets",
        "allow_shell_execution": False,
        "allow_network_access": True,
        "require_confirmation_for_installers": True,
    },
    "external_integrations": {"enabled":True,"default_mode":"metadata_only","allow_remote_providers":False,"allow_paid_providers":False,"allow_external_execution":False,"require_approval_for_external_actions":True,"block_secret_egress":True,"max_providers":32,"max_history_items":50,"health_cache_seconds":60,"max_retries":1},
    "external_provider_flags": {"telegram_enabled":False,"discord_enabled":False,"email_smtp_enabled":False,"email_api_enabled":False,"slack_enabled":False,"matrix_enabled":False,"whatsapp_enabled":False,"github_enabled":False,"mcp_local_enabled":False,"mcp_remote_enabled":False,"external_plugins_enabled":False,"nvidia_nim_enabled":False,"openai_compatible_enabled":False},
    "telegram": {"enabled":False,"transport":"long_polling","polling_enabled":False,"webhook_enabled":False,"require_authorized_chat":True,"allow_inbound_text":True,"allow_outbound_text":True,"allow_commands":True,"allow_media":False,"allow_documents":False,"allow_voice":False,"allow_group_chats":False,"allow_channel_posts":False,"allow_scheduled_send":False,"require_approval_for_send":True,"max_message_chars":3900,"max_updates_per_poll":20,"poll_timeout_seconds":10,"max_retries":2,"rate_limit_window":60,"max_sends_per_window":5,"save_history":True,"redact_sensitive_values":True},
    "discord":{"enabled":False,"transport":"bot_api","allow_send":False,"allow_inbound":False,"allow_webhook":False,"allow_attachments":False,"require_approval":True,"max_message_chars":1900,"max_sends_per_window":3,"max_retries":1},
    "email_connector":{"smtp_enabled":False,"api_enabled":False,"allow_send":False,"allow_read":False,"allow_html":False,"allow_attachments":False,"allow_cc":False,"allow_bcc":False,"allow_bulk":False,"require_approval":True,"max_recipients":1,"max_body_chars":10000,"max_retries":1},
    "slack":{"enabled":False,"allow_send":False,"allow_inbound":False,"allow_attachments":False,"require_approval":True,"max_message_chars":3900,"max_sends_per_window":3,"max_retries":1},
    "github_provider":{"enabled":False,"transport":"gh_cli","allow_read":True,"allow_issue_write":False,"allow_pr_write":False,"allow_release_write":False,"allow_merge":False,"allow_workflow_execute":False,"allow_admin":False,"allowed_repositories":["yeshwanthpullur/JarvisOS"],"require_approval_for_writes":True,"max_results":20,"max_body_chars":4000,"max_retries":1,"health_cache_seconds":60,"save_history":True,"redact_sensitive_values":True},
    "desktop": {
        "enabled": True,
        "platform": "windows",
        "downloads_folder": "",
    },
    "mobile": {
        "enabled": False,
        "api_enabled": False,
        "automation_enabled": True,
        "automation_mode": "planning_only",
        "automation_adapter": "planning-only",
        "audit_retention": 100,
        "live_control_enabled": False,
        "store_private_data": False,
    },
}
