"""Default configuration values for JARVIS OS."""

from __future__ import annotations

from typing import Any, Final


DEFAULT_CONFIG: Final[dict[str, Any]] = {
    "general": {
        "app_name": "JARVIS OS",
        "environment": "development",
        "debug": False,
    },
    "logging": {
        "level": "INFO",
        "log_dir": "logs",
        "log_file": "jarvis-os.log",
        "max_bytes": 1_048_576,
        "backup_count": 5,
    },
    "memory": {
        "enabled": True,
        "storage_dir": "memory",
        "task_store_dir": "data/tasks",
        "vector_index_dir": "data/vector-indexes",
        "local_only": True,
        "auto_remember": False,
        "auto_session_summary": True,
        "max_records": 2000,
        "max_search_results": 12,
        "max_context_items": 8,
        "max_context_chars": 6000,
        "audit_enabled": True,
        "audit_retention": 100,
        "default_retention_days": 3650,
        "sensitive_storage_enabled": False,
        "consolidation_enabled": True,
        "secret_detection_enabled": True,
        "authority": "memory_intelligence", "automatic_write": False, "conflict_detection": True, "provenance_required": True,
        "semantic_primary": "qdrant", "semantic_backup": "chromadb", "graph_provider": "graphiti", "graph_enabled": False,
        "memory_framework_provider": "mem0", "memory_framework_enabled": False, "embedding_provider": "local", "embedding_model": None,
        "retrieval_max_results": 8, "retrieval_context_budget_chars": 3000,
    },
    "conversation": {
        "enabled": True,
        "max_turns": 12,
        "max_topics": 6,
        "summary_threshold": 8,
        "reference_resolution": True,
        "clarification_enabled": True,
        "max_context_chars": 6000,
    },
    "brain": {
        "enabled": True,
        "vault_path": "data/obsidian-vault",
        "vault_name": "Jarvis Brain",
        "auto_create_vault": True,
        "daily_note_format": "%Y-%m-%d",
    },
    "models": {
        "default_model": "llama3.2:1b",
        "fallback_model": "",
        "allow_local_models": True,
        "enabled": True,
        "local_only_default": True,
        "allow_cloud_providers": False,
        "default_chat_provider": "ollama_text",
        "default_reasoning_provider": "ollama_text",
        "default_coding_provider": "ollama_text",
        "default_vision_provider": "ollama_vision",
        "max_providers": 32,
        "max_models_per_provider": 32,
        "max_route_explanations": 8,
        "hardware_discovery_enabled": True,
        "runtime_enabled": True, "runtime_default_policy": "local_preferred", "runtime_prefer_local": True,
        "runtime_allow_remote": False, "runtime_allow_paid": False, "runtime_allow_auto_start": False,
        "runtime_allow_auto_download": False, "runtime_max_concurrent": 2, "runtime_default_timeout_seconds": 60,
        "runtime_health_cache_seconds": 60, "runtime_max_fallbacks": 2, "runtime_resource_reserve_ratio": 0.2,
        "runtime_save_history": True, "runtime_redact_sensitive_values": True,
    },
    "providers": {
        "default_provider": "ollama",
        "enabled_providers": ["ollama"],
        "timeout_seconds": 30,
        "max_retries": 2,
        "track_costs": True,
        "definitions": {
            "openai": {
                "kind": "openai",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.openai.com",
                "api_key_env": "OPENAI_API_KEY",
                "metadata": {
                    "provider_family": "openai",
                },
            },
            "anthropic": {
                "kind": "anthropic",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.anthropic.com",
                "api_key_env": "ANTHROPIC_API_KEY",
                "metadata": {
                    "provider_family": "anthropic",
                },
            },
            "google": {
                "kind": "google_gemini",
                "enabled": False,
                "local_only": False,
                "base_url": "https://generativelanguage.googleapis.com",
                "api_key_env": "GOOGLE_API_KEY",
                "metadata": {
                    "provider_family": "gemini",
                },
            },
            "deepseek": {
                "kind": "deepseek",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.deepseek.com",
                "api_key_env": "DEEPSEEK_API_KEY",
                "metadata": {
                    "provider_family": "deepseek",
                },
            },
            "mistral": {
                "kind": "mistral",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.mistral.ai",
                "api_key_env": "MISTRAL_API_KEY",
                "metadata": {
                    "provider_family": "mistral",
                },
            },
            "groq": {
                "kind": "groq",
                "enabled": False,
                "local_only": False,
                "base_url": "https://api.groq.com",
                "api_key_env": "GROQ_API_KEY",
                "metadata": {
                    "provider_family": "groq",
                },
            },
            "openrouter": {
                "kind": "openrouter",
                "enabled": False,
                "local_only": False,
                "base_url": "https://openrouter.ai/api",
                "api_key_env": "OPENROUTER_API_KEY",
                "metadata": {
                    "provider_family": "openrouter",
                },
            },
            "zenmux": {
                "kind": "zenmux",
                "enabled": True,
                "local_only": False,
                "base_url": "https://api.zenmux.ai",
                "api_key_env": "ZENMUX_API_KEY",
                "metadata": {
                    "provider_family": "zenmux",
                },
            },
            "local": {
                "kind": "local",
                "enabled": False,
                "local_only": True,
                "base_url": "http://127.0.0.1:11434",
                "metadata": {
                    "local": True,
                    "runtime": "openai-compatible",
                },
            },
            "ollama": {
                "kind": "ollama",
                "enabled": True,
                "local_only": True,
                "base_url": "http://127.0.0.1:11434",
                "preferred_model": "llama3.2:1b",
                "default_model": "llama3.2:1b",
                "timeout_seconds": 60,
                "max_retries": 1,
                "metadata": {
                    "local": True,
                    "runtime": "ollama",
                },
            },
        },
    },
    "agents": {
        "enabled": True,
        "max_concurrent_agents": 4,
        "workspace_dir": "data/agent-workspaces",
        "max_agents_per_coordination": 4,
        "max_subtasks_per_coordination": 8,
        "max_recursion_depth": 1,
        "max_retries_per_subtask": 1,
        "max_total_timeout_seconds": 180,
        "default_mode": "plan_only",
        "max_agents": 64,
        "max_capabilities_per_agent": 32,
        "max_output_chars": 8000,
        "require_approval_for_high_risk": True,
        "local_only_default": True,
        "register_future_placeholders": True,
        "show_future_agents": True,
        "max_diagnostic_agents": 25,
        "max_diagnostic_capabilities": 40,
        "default_specialist_mode": "plan_only",
        "block_critical_future_agents": True,
    },
    "prime": {
        "enabled": True,
        "default_execution_mode": "plan_only",
        "max_plan_steps": 8,
        "max_reason_chars": 600,
        "max_fallbacks": 3,
        "require_approval_for_high_risk": True,
        "block_critical_risk": True,
        "local_only": True,
    },
    "skills": {
        "enabled": True,
        "allow_external_plugins": False,
        "allow_mcp": False,
        "default_execution_mode": "plan_only",
        "max_skills": 512,
        "max_capabilities_per_skill": 32,
        "max_output_chars": 8000,
        "require_approval_for_side_effects": True,
        "block_secrets_access": True,
    },
    "research": {
        "enabled": True,
        "default_depth": "standard",
        "max_plan_steps": 5,
        "max_evidence_items": 5,
        "max_snippet_chars": 320,
        "max_summary_chars": 1200,
        "allow_web_read_only": True,
        "allow_external_search_api": False,
        "save_history": True,
        "local_only": True,
        "require_citations_for_web_claims": True,
        "allow_external_search": False,
        "allow_browser_retrieval": True,
        "allow_github": True,
        "allow_mcp": True,
        "allow_plugins": True,
        "prefer_primary_sources": True,
        "enable_counterevidence": True,
        "max_queries_quick": 2,
        "max_queries_standard": 5,
        "max_queries_deep": 8,
        "max_sources_quick": 4,
        "max_sources_standard": 8,
        "max_sources_deep": 12,
        "max_pages_per_domain": 3,
        "max_chars_per_source": 6000,
        "max_total_chars": 24000,
        "max_followup_rounds": 2,
        "search_timeout_seconds": 20,
        "retrieval_timeout_seconds": 20,
        "total_timeout_seconds": 120,
        "max_concurrent_requests": 2,
        "cache_enabled": True,
        "cache_ttl_seconds": 3600,
        "max_history_items": 25,
        "redact_sensitive_values": True,
        "primary_crawler": "crawl4ai", "backup_crawler": "firecrawl", "max_pages": 5, "max_depth": 1,
        "network_allowed": False, "citations_required": True,
    },
    "coding": {
        "enabled": True,
        "default_mode": "plan_only",
        "max_plan_steps": 6,
        "max_files_listed": 20,
        "max_diff_chars": 4000,
        "max_history_items": 25,
        "allow_write_operations": False,
        "allow_command_execution": False,
        "require_approval_for_write": True,
        "require_approval_for_push": True,
        "block_secrets_access": True,
        "aider_enabled": False, "open_interpreter_enabled": False, "external_mode": "plan_only", "external_environment": "tools/coding/.venv",
        "external_file_write_allowed": False, "external_shell_allowed": False, "external_network_allowed": False, "external_approval_required": True,
        "max_files_per_change": 10, "max_diff_lines": 1000, "max_runtime_seconds": 600,
    },
    "knowledge": {
        "enabled": True,
        "default_retrieval_mode": "auto",
        "allow_persistent_index": True,
        "allow_remote_embeddings": False,
        "allow_remote_reranking": False,
        "auto_admit_research": False,
        "max_sources": 100,
        "max_records": 1000,
        "max_chunks_per_record": 50,
        "max_chunk_chars": 800,
        "chunk_overlap_chars": 80,
        "max_results": 5,
        "max_context_chunks": 5,
        "max_context_chars": 4000,
        "prefer_fresh": True,
        "prefer_primary_sources": True,
        "enable_lexical": True,
        "enable_semantic": False,
        "enable_hybrid": False,
        "enable_reranking": False,
        "save_history": True,
        "redact_sensitive_values": True,
    },
    "orchestrator": {
        "enabled": True,
        "max_parallel_agents": 2,
        "max_sessions": 25,
        "default_timeout_seconds": 180,
        "max_retry_count": 1,
        "enable_parallel_execution": True,
        "enable_partial_results": True,
        "enable_recovery": True,
        "enable_event_log": True,
        "enable_metrics": True,
        "enable_audit": True,
        "max_context_versions": 10,
        "max_event_history": 200,
        "max_message_history": 100,
        "max_delegation_depth": 3,
    },
    "documents": {
        "enabled": True,
        "default_mode": "plan_only",
        "max_file_bytes": 1000000,
        "max_extract_chars": 4000,
        "max_history_items": 25,
        "allow_pdf": False,
        "allow_office": False,
        "allow_ocr": False,
        "allow_cloud_parsing": False,
        "allow_bulk_ingestion": False,
        "save_history": True,
        "store_extracted_content": False,
        "local_only": True,
        "primary_parser": "docling", "backup_parser": "marker", "max_pages": 100, "allow_private_documents": True,
        "allow_secret_files": False, "require_citations": True, "memory_update_default": False, "knowledge_update_default": False,
        "parser_timeout_seconds": 120,
    },
    "browser": {
        "enabled": True,
        "default_mode": "read_only",
        "allow_interactive": False,
        "allow_login": False,
        "allow_forms": False,
        "allow_purchases": False,
        "allow_downloads": False,
        "allow_cookies": False,
        "allow_sessions": False,
        "allow_external_automation": False,
        "max_history_items": 25,
        "save_history": True,
        "local_only": True,
        "primary": "browser_use", "backup": "playwright", "approval_required": True, "max_session_minutes": 10,
        "allowed_domains": [], "blocked_domains": [], "screenshots_allowed": False, "uploads_allowed": False, "form_submit_allowed": False,
    },
    "scheduler": {
        "enabled": True,
        "default_mode": "plan_only",
        "allow_background_runner": False,
        "allow_os_cron": False,
        "allow_task_scheduler": False,
        "allow_notifications": False,
        "minimum_cadence_minutes": 60,
        "max_runs": 100,
        "max_history_items": 25,
        "save_history": True,
        "local_only": True,
    },
    "communication": {
        "enabled": True,
        "default_mode": "draft_only",
        "allow_sending": False,
        "allow_external_providers": False,
        "allow_contact_access": False,
        "allow_bulk_messages": False,
        "allow_social_posting": False,
        "allow_credentials_access": False,
        "max_history_items": 25,
        "save_history": True,
        "local_only": True,
        "external_enabled": True,
        "external_require_approval": True,
        "external_allow_attachments": False,
        "external_allow_scheduled_send": False,
        "external_max_message_chars": 4000,
        "external_max_attachments": 0,
        "external_max_sends_per_window": 3,
        "external_rate_window_seconds": 60,
        "external_max_retries": 1,
        "external_duplicate_protection": True,
        "external_redact_sensitive_values": True,
        "external_block_secrets": True,
    },
    "adapters": {
        "enabled": True,
        "default_mode": "plan_only",
        "allow_mcp_runtime": False,
        "allow_plugin_install": False,
        "allow_external_tool_execution": False,
        "allow_network_connectors": False,
        "allow_webhooks": False,
        "allow_command_execution": False,
        "allow_file_writes": False,
        "allow_message_sending": False,
        "allow_background_servers": False,
        "allow_credentials_access": False,
        "max_plan_steps": 8,
        "max_manifests_listed": 25,
        "max_history_items": 25,
        "save_history": True,
        "redact_sensitive_values": True,
    },
    "models_advanced": {
        "enabled": True,
        "default_mode": "planning_only",
        "local_first": True,
        "allow_cloud_providers": False,
        "allow_provider_install": False,
        "allow_model_download": False,
        "allow_runtime_start": False,
        "allow_docker": False,
        "allow_gpu_diagnostics": False,
        "allow_credentials_access": False,
        "max_plan_steps": 8,
        "max_providers_listed": 25,
        "max_history_items": 25,
        "save_history": True,
        "redact_sensitive_values": True,
        "block_cloud_without_approval": True,
        "require_approval_for_runtime": True,
        "require_approval_for_downloads": True,
    },
    "evaluation": {
        "enabled": True,
        "default_mode": "local_only",
        "allow_cloud_telemetry": False,
        "allow_remote_logging": False,
        "allow_background_runner": False,
        "save_history": True,
        "max_cases_per_suite": 100,
        "max_output_chars": 8000,
        "max_history_items": 25,
        "redact_sensitive_values": True,
        "block_private_paths": True,
        "require_local_only": True,
        "fail_on_truthfulness_mismatch": True,
        "fail_on_secret_leakage": True,
        "fail_on_path_leakage": True,
    },
    "release_readiness": {
        "enabled": True,
        "validation_only": True,
        "require_all_blocking_gates": True,
        "allow_tag_creation": False,
        "allow_release_creation": False,
        "allow_deployment": False,
        "require_clean_repository": True,
        "require_origin_match": True,
        "require_vercel_status_only": True,
        "max_gates": 50,
        "max_output_chars": 8000,
    },
    "execution": {
        "enabled": True,
        "default_mode": "plan_only",
        "local_first": True,
        "allow_file_writes": True,
        "allow_command_execution": True,
        "allow_git_writes": True,
        "allow_browser_read": True,
        "allow_browser_actions": False,
        "allow_notifications": True,
        "allow_scheduler_runner": True,
        "allow_communication_send": False,
        "allow_mcp_execution": False,
        "allow_model_runtime_start": False,
        "allow_external_network": False,
        "allow_background_execution": False,
        "allow_secrets_access": False,
        "allow_credentials_access": False,
        "require_approval_for_side_effects": True,
        "block_critical_actions": True,
        "max_plan_steps": 8,
        "max_history_items": 50,
        "save_history": True,
        "redact_sensitive_values": True,
        "block_private_paths": True,
    },
    "approvals": {
        "enabled": True,
        "default_mode": "explicit_only",
        "require_explicit_approval": True,
        "allow_implied_approval": False,
        "allow_broad_approval": False,
        "allow_permanent_approval": False,
        "allow_secret_access_approval": False,
        "allow_critical_action_approval": False,
        "default_ttl_seconds": 900,
        "max_pending": 50,
        "max_history_items": 100,
        "save_history": True,
        "redact_sensitive_values": True,
        "block_private_paths": True,
        "require_resource_scope": True,
        "require_permission_scope": True,
    },
    "broker": {
        "enabled": True,
        "default_mode": "dry_run",
        "allow_actual_execution": True,
        "allow_unapproved_execution": False,
        "require_policy_check": True,
        "require_approval_for_side_effects": True,
        "require_permission_scope": True,
        "allow_external_tools": False,
        "allow_network_tools": False,
        "allow_background_tools": False,
        "block_critical_actions": True,
        "max_plan_steps": 8,
        "max_history_items": 50,
        "save_history": True,
        "redact_sensitive_values": True,
        "block_private_paths": True,
        "store_payloads": False,
    },
    "tools": {
        "maximum_per_request": 3,
        "maximum_per_coordination": 6,
        "maximum_retries": 1,
        "maximum_timeout_seconds": 30,
        "maximum_concurrent": 2,
        "maximum_output_bytes": 64000,
        "maximum_argument_bytes": 16000,
        "maximum_chained_depth": 1,
        "maximum_dry_run_seconds": 5,
        "maximum_history": 200,
    },
    "phase6": {
        "enabled": True,
        "core_python_preference": "3.11-3.12",
        "isolate_external_tools": True,
        "allow_global_install_repair": False,
        "allow_automatic_install": False,
        "allow_automatic_model_download": False,
        "tool_default_enabled": False,
        "local_only": True,
        "cloud_fallback": False,
        "dependency_audit_timeout_seconds": 20,
        "health_check_timeout_seconds": 3,
        "max_diagnostic_items": 32,
    },
    "planning": {"maximum_steps":12,"maximum_milestones":5,"maximum_alternatives":3,"maximum_dependencies_per_step":4,"maximum_plan_depth":2,"maximum_retries":1,"maximum_replans":3,"maximum_concurrent":2,"maximum_agents":3,"maximum_tools":4,"maximum_timeout_seconds":90,"maximum_versions":10,"maximum_output_bytes":100000,"maximum_assumptions":8},
    "workflow": {
        "enabled": True, "max_active": 4, "max_parallel_steps": 2, "max_pending": 25,
        "default_timeout_seconds": 300, "max_retry_count": 2, "default_checkpoint_interval": 1,
        "enable_parallel_execution": True, "enable_pause_resume": True, "enable_recovery": True,
        "enable_metrics": True, "enable_audit": True, "max_event_history": 200,
        "max_checkpoint_history": 50, "max_artifacts": 50, "max_runtime_hours": 4,
    },
    "reliability": {"enabled":True,"monitor_interval_seconds":30,"enable_metrics":True,"enable_diagnostics":True,"enable_health_dashboard":True,"enable_alerts":True,"enable_circuit_breakers":True,"enable_fault_isolation":True,"enable_self_healing":False,"max_retry_attempts":2,"max_health_history":200,"max_alert_history":100,"max_metric_history":500,"max_parallel_health_checks":4},
    "governance": {"enabled":True,"zero_trust_enabled":True,"audit_enabled":True,"compliance_enabled":True,"policy_strict_mode":True,"risk_enabled":True,"identity_enabled":True,"authorization_enabled":True,"trust_enabled":True,"event_correlation_enabled":True,"dashboard_enabled":True,"metrics_enabled":True,"policy_registry_enabled":True,"retention_enabled":True,"policy_versioning_enabled":True,"incident_tracking_enabled":True,"max_security_events":200,"max_audit_records":500,"max_policy_cache":100,"max_trust_cache":100,"max_incidents":100},
    "voice":{"enabled":False,"mode":"off","language":"en-US","local_only":True,"privacy_mode":"standard","input_enabled":False,"output_enabled":False,"input_backend":"offline-stt","output_backend":"windows-sapi","input_device":None,"output_device":None,"confidence_threshold":0.75,"confirmation_threshold":0.6,"max_capture_seconds":30,"silence_timeout_seconds":3,"max_audio_size":20000000,"max_transcript_length":4000,"max_spoken_response_length":500,"max_auto_speech_chars":12000,"rate":0,"volume":100,"raw_audio_persistence":False,"retention_limit":0,"temp_audio_lifetime_seconds":300,"voice_input_audit_retention":50,"stt_model_path":None,"stt_executable":None,"wake_word_enabled":False,"wake_word_backend":None,"activation_phrase":"jarvis","interruption_enabled":True,"temp_directory":"data/voice-temp","allowed_audio_directories":["data/voice-input"],"stt_primary":"faster_whisper","stt_backup":"vosk","tts_primary":"piper","tts_backup":"windows_sapi","retain_audio":False,"continuous_listening":False,"max_session_minutes":30,"idle_timeout_seconds":15},
    "vision":{"enabled":True,"local_only":True,"privacy_mode":"standard","provider":"ollama","model":"llava","ollama_host":"http://127.0.0.1:11434","max_image_size":20000000,"timeout_seconds":60,"audit_enabled":True,"audit_retention":100,"store_image_content":False,"allowed_directories":[],"ocr_enabled":False,"ocr_primary":"paddleocr","ocr_backup":"easyocr","camera_enabled":False,"retain_frames":False,"camera_max_session_minutes":10,"cloud_processing_allowed":False,"max_images_per_request":4},
    "image_generation": {
        "enabled": False,
        "default_provider": "unavailable",
        "local_only": True,
        "output_dir": "data/image_generation",
        "max_prompt_chars": 600,
        "max_negative_prompt_chars": 300,
        "save_metadata": True,
        "allow_overwrite": False,
        "safety_filter_enabled": True,
    },
    "video_editing": {
        "enabled": False,
        "default_provider": "unavailable",
        "local_only": True,
        "output_dir": "data/video_editing",
        "max_prompt_chars": 600,
        "max_source_media_items": 12,
        "save_metadata": True,
        "allow_overwrite": False,
        "safety_filter_enabled": True,
    },
    "sync":{"enabled":False,"mode":"off","adapter":"local-queue","automatic_sync":False,"remote_endpoint":None,"maximum_item_size":8192,"maximum_queue_items":100,"maximum_batch_size":10,"maximum_attempts":3,"completed_retention_count":25,"audit_retention_count":100,"maximum_nested_depth":4,"maximum_string_length":1000,"conflict_strategy":"manual","encryption_required":True,"sync_raw_audio":False,"sync_raw_images":False,"sync_raw_documents":False,"sync_conversations":False,"sync_secrets":False},
    "web_automation":{"enabled":True,"mode":"read_only","adapter":"read-only-http","allow_local_targets":False,"allow_http":False,"audit_retention":100,"action_timeout_seconds":8,"maximum_redirects":5,"maximum_response_bytes":524288,"maximum_preview_characters":2000,"store_page_content":False,"store_screenshots":False},
    "interface": {
        "enabled": False,
        "host": "127.0.0.1",
        "port": 8765,
        "open_browser": True,
        "theme": "system",
        "default_view": "chat",
        "event_transport": "sse",
        "max_request_size": 65536,
        "max_response_size": 262144,
        "max_log_entries": 200,
        "max_activity_entries": 200,
        "max_history_messages": 200,
        "request_timeout": 120,
        "event_timeout": 30,
        "allow_remote": False,
        "allowed_origins": ["http://127.0.0.1:8765", "http://localhost:8765"],
        "session_token_lifetime": 14400,
        "safe_markdown": True,
        "show_provider_metadata": True,
        "show_activity_panel": True,
        "compact_mode": False,
    },
    "plugins": {
        "enabled": True,
        "plugin_dir": "plugins",
        "allow_user_plugins": False,
        "auto_discover": False,
        "auto_enable": False,
        "compatibility_version": "0.1",
        "allow_external": True, "allow_local_development": True,
        "allow_inprocess_external": False, "allow_subprocess": False,
        "allow_network": False, "allow_filesystem_write": False,
        "allow_installation": False, "allow_updates": False, "allow_uninstall": False,
        "require_integrity_check": True, "require_approval_for_enable": True,
        "require_approval_for_side_effects": True, "max_registered": 64,
        "max_enabled": 8, "max_output_chars": 8000, "execution_timeout_seconds": 30,
        "max_concurrent": 1, "save_history": True, "max_history_items": 100,
        "redact_sensitive_values": True,
    },
    "downloads": {
        "download_dir": "data/downloads",
        "max_concurrent_downloads": 3,
        "verify_integrity": True,
    },
    "automation": {
        "enabled": False,
        "queue_dir": "data/automation-queue",
        "max_concurrent_jobs": 2,
        "desktop_enabled": False, "desktop_approval_required": True, "filesystem_write_allowed": False, "filesystem_delete_allowed": False,
        "commands_enabled": False, "allow_arbitrary_shell": False, "command_approval_required": True, "scheduler_allow_execution_actions": False,
        "system_read_status_allowed": True, "system_settings_change_allowed": False,
    },
    "connectors": {"enabled": True, "auto_discovery": True, "auto_enable": False, "auto_authenticate": False, "communication_send_default": False, "mcp_remote_enabled": False, "mcp_auto_start_servers": False, "external_plugins_enabled": False, "plugin_auto_install": False, "plugin_auto_update": False, "max_connectors": 64},
    "observability": {"enabled": True, "local_only": True, "telemetry_upload": False, "metrics_enabled": True, "metrics_retention_hours": 24, "traces_enabled": True, "traces_include_payloads": False, "profiling_enabled": False, "alerts_enabled": True, "prometheus_enabled": False, "opentelemetry_enabled": False, "max_metrics": 500, "max_traces": 200},
    "security": {
        "secrets_dir": "data/secrets",
        "allow_shell_execution": False,
        "allow_network_access": True,
        "require_confirmation_for_installers": True,
    },
    "external_integrations": {"enabled":True,"default_mode":"metadata_only","allow_remote_providers":False,"allow_paid_providers":False,"allow_external_execution":False,"require_approval_for_external_actions":True,"block_secret_egress":True,"max_providers":32,"max_history_items":50,"health_cache_seconds":60,"max_retries":1},
    "external_provider_flags": {"telegram_enabled":False,"discord_enabled":False,"email_smtp_enabled":False,"email_api_enabled":False,"slack_enabled":False,"matrix_enabled":False,"whatsapp_enabled":False,"github_enabled":False,"mcp_local_enabled":False,"mcp_remote_enabled":False,"external_plugins_enabled":False,"nvidia_nim_enabled":False,"openai_compatible_enabled":False},
    "telegram": {"enabled":False,"transport":"long_polling","polling_enabled":False,"webhook_enabled":False,"require_authorized_chat":True,"allow_inbound_text":True,"allow_outbound_text":True,"allow_commands":True,"allow_media":False,"allow_documents":False,"allow_voice":False,"allow_group_chats":False,"allow_channel_posts":False,"allow_scheduled_send":False,"require_approval_for_send":True,"max_message_chars":3900,"max_updates_per_poll":20,"poll_timeout_seconds":10,"max_retries":2,"rate_limit_window":60,"max_sends_per_window":5,"save_history":True,"redact_sensitive_values":True},
    "discord":{"enabled":False,"transport":"bot_api","allow_send":False,"allow_inbound":False,"allow_webhook":False,"allow_attachments":False,"require_approval":True,"max_message_chars":1900,"max_sends_per_window":3,"max_retries":1},
    "email_connector":{"smtp_enabled":False,"api_enabled":False,"allow_send":False,"allow_read":False,"allow_html":False,"allow_attachments":False,"allow_cc":False,"allow_bcc":False,"allow_bulk":False,"require_approval":True,"max_recipients":1,"max_body_chars":10000,"max_retries":1},
    "slack":{"enabled":False,"allow_send":False,"allow_inbound":False,"allow_attachments":False,"require_approval":True,"max_message_chars":3900,"max_sends_per_window":3,"max_retries":1},
    "github_provider":{"enabled":False,"transport":"gh_cli","allow_read":True,"allow_issue_write":False,"allow_pr_write":False,"allow_release_write":False,"allow_merge":False,"allow_workflow_execute":False,"allow_admin":False,"allowed_repositories":["yeshwanthpullur/JarvisOS"],"require_approval_for_writes":True,"max_results":20,"max_body_chars":4000,"max_retries":1,"health_cache_seconds":60,"save_history":True,"redact_sensitive_values":True},
    "mcp":{"enabled":True,"allow_local_stdio":True,"allow_local_http":True,"allow_remote_http":False,"allow_tool_execution":False,"allow_resource_read":True,"allow_prompts":False,"allow_installation":False,"allow_scheduled_execution":False,"require_approval_for_side_effects":True,"max_servers":16,"max_tools_per_server":50,"max_resources_per_server":50,"max_result_chars":8000,"max_concurrent_calls":2,"startup_timeout_seconds":10,"call_timeout_seconds":30,"max_retries":1,"health_cache_seconds":60,"save_history":True,"max_history_items":100,"redact_sensitive_values":True},
    "desktop": {
        "enabled": True,
        "platform": "windows",
        "downloads_folder": "",
    },
    "mobile": {
        "enabled": False,
        "api_enabled": False,
        "automation_enabled": True,
        "automation_mode": "planning_only",
        "automation_adapter": "planning-only",
        "audit_retention": 100,
        "live_control_enabled": False,
        "store_private_data": False,
    },
}
