"""Non-executing adapter contract for future external providers."""
from __future__ import annotations
from typing import Protocol
from .models import ExternalActionRequest,ExternalActionResult,ProviderHealth
class ExternalProviderAdapter(Protocol):
 def health(self)->ProviderHealth:...
 def validate(self,request:ExternalActionRequest)->ExternalActionResult:...
 def execute(self,request:ExternalActionRequest)->ExternalActionResult:...
